### ISSUE TITLE
Implementar test de rendimiento de ServidorConPadres (JETM)

### ISSUE THREAD

**Issue by srjavimoure** [andreu-barro/VVS#12]
Implementar test de rendimiento de ServidorConPadres (JETM): ServidorConPadresRendimientoTest

**Comment by eoitaven** [comment]
Implementado, pero no lo veo en el Site, comprobar que aparecen los resultados. En travis compila sin problemas, así que no se si es problema de llenar el site

**Comment by eoitaven** [comment]
Encontrado bug en el que no genera bien el documento de los test de JETM y por eso no aparece en el site. Pasa los test, por lo que están creados los test de ServidorConPadres (JETM)
