### ISSUE TITLE
Implementar test de rendimiento de ServidorNormal (JETM)

### ISSUE THREAD

**Issue by srjavimoure** [andreu-barro/VVS#13]
Implementar test de rendimiento de ServidorNormal (JETM): ServidorNormalRendimientoTest

**Comment by eoitaven** [comment]
Se implementan los test de rendimiento JETM Timing Report
![jemt](https://cloud.githubusercontent.com/assets/15674398/11797003/4026f6e4-a2c0-11e5-8aca-cc4e8cdbb90b.PNG)
