### ISSUE TITLE
Abstracción

### ISSUE THREAD

**Issue by iagocanalejas** [andreu-barro/VVS#3]
En la interfaz de Contenido no se especifican métodos set para titulo y duración por lo que para cumplir con la abstracción seria mas correcto utilizar los constructores para inicializar los objetos.

**Comment by srjavimoure** [comment]
@iagocanalejas Quedaban sets sin eliminar y ya han sido eliminados en una versión que no habíamos subido. Vuelve a bajar la versión y confirmame.

**Comment by lauramcastro** [comment]
@srjavimoure si sabes que has arreglado la issue puedes cerrarla sin pedir confirmación a @iagocanalejas... es decir, dado que lo que hay que comprobar en esta issue es la presencia/ausencia de un método, es algo objetivo, no le estás pidiendo que evalúe el rendimiento en su máquina o cosas así... si los métodos ya no están, no están y listo.
