### ISSUE TITLE
Implementación de la clase Token

### ISSUE THREAD

**Issue by iagocanalejas** [andreu-barro/VVS#5]
La implementación de la clase token es anti-intuitiva ya que se implementa como un singleton algo que de lo que se deberían crear instancias. Lo que se hace en su lugar es guardar una lista de strings con su conteo asociado en la clase Token.

Posible Solucion: Seria mas simple que la clase Token simplemente tuviera un String y un long y fueran los servidores los encargados de almacenar su propio  token de administracion asi como de crear sus propios tokens.

Prueba:

```
    GenericServidor server = new ServidorNormal("P",new ArrayList<Contenido>());
    String t = server.alta();
    GenericServidor server1 = new ServidorNormal("P1",new ArrayList<Contenido>());

    Cancion c = new Cancion();
    c.setTitulo("a");

    server1.agregar(c, "ADMINISTRADOR");
    assertTrue(server1.buscar("a", t).size()>0);
```

Creando un token para server y despues creando un servidor nuevo (server1) los tokens dados de alta para el primer servidor son validos para el segundo.

**Comment by andreu-barro** [comment]
@srjavimoure 
Eliminada implementación singleton en Token, ahora se solicita al crear servidor. Esto permitirá que varios servidores puedan compartir tokens si desean (por ej. padres e hijos o servidores de respaldo).

**Comment by lauramcastro** [comment]
Buen trabajo @iagocanalejas aportando una prueba. ¡Espero verla en el repositorio de ambos equipos! ;-)
